# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarjeta_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tarjeta_ui(object):
    def setupUi(self, tarjeta_ui):
        tarjeta_ui.setObjectName(_fromUtf8("tarjeta_ui"))
        tarjeta_ui.resize(1873, 1038)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tarjeta_ui.sizePolicy().hasHeightForWidth())
        tarjeta_ui.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(tarjeta_ui)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(tarjeta_ui)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1829, 974))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_6 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.textEdit = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_6.addWidget(self.textEdit, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_6.addWidget(self.pushButton, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 4, 0, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_3.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab_4)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.gridLayout_4.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.tab_5)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.gridLayout_5.addWidget(self.textBrowser_3, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget_2, 1, 0, 3, 1)
        self.textEdit_2 = QtGui.QTextEdit(self.tab_2)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.gridLayout_2.addWidget(self.textEdit_2, 1, 1, 1, 1)
        self.textEdit_3 = QtGui.QTextEdit(self.tab_2)
        self.textEdit_3.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.gridLayout_2.addWidget(self.textEdit_3, 3, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_2.addWidget(self.pushButton_4, 5, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 4, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.tab_2)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_2.addWidget(self.pushButton_5, 6, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.tab_6)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.gridLayout_7.addWidget(self.textBrowser_4, 1, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.tab_6)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_7.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_6)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 0, 1, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.tab_6)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_7.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.tab_6)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_7.addWidget(self.pushButton_7, 3, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 2)
        self.gridLayout_7.setColumnStretch(1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(tarjeta_ui)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(tarjeta_ui)

    def retranslateUi(self, tarjeta_ui):
        tarjeta_ui.setWindowTitle(_translate("tarjeta_ui", "Form", None))
        self.pushButton.setText(_translate("tarjeta_ui", "Save Words", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("tarjeta_ui", "Import Words", None))
        self.label.setText(_translate("tarjeta_ui", "Front", None))
        self.label_2.setText(_translate("tarjeta_ui", "Back", None))
        self.pushButton_2.setText(_translate("tarjeta_ui", "Add Card", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("tarjeta_ui", "SpanishDict", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("tarjeta_ui", "DLE", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("tarjeta_ui", "WordReference", None))
        self.pushButton_4.setText(_translate("tarjeta_ui", "Write Word", None))
        self.pushButton_3.setText(_translate("tarjeta_ui", "Next Word", None))
        self.pushButton_5.setText(_translate("tarjeta_ui", "Skip Word (Remove From List)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("tarjeta_ui", "Create Cards", None))
        self.label_3.setText(_translate("tarjeta_ui", "Word", None))
        self.pushButton_6.setText(_translate("tarjeta_ui", "Lookup", None))
        self.pushButton_7.setText(_translate("tarjeta_ui", "Add To List", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("tarjeta_ui", "Quick Lookup", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    tarjeta_ui = QtGui.QWidget()
    ui = Ui_tarjeta_ui()
    ui.setupUi(tarjeta_ui)
    tarjeta_ui.show()
    sys.exit(app.exec_())

